import type { MetadataRoute } from "next"

/**
 * /robots.txt
 *
 * Generated by Next.js at build time from this file. Tells crawlers:
 *   - Everything is fair game except API routes and the offline fallback.
 *   - The sitemap lives at /sitemap.xml (also generated by Next.js — see app/sitemap.ts).
 *
 * Without this file the route returned 404 and Google had to guess where the sitemap
 * lived; with it we get an explicit instruction set in the format crawlers expect.
 */
export default function robots(): MetadataRoute.Robots {
  const baseUrl = "https://friendsforum.org"

  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/api/",
          "/offline",
          "/_next/",
        ],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  }
}
