import type { MetadataRoute } from "next"

/**
 * /sitemap.xml
 *
 * Generated by Next.js from this file. Lists all the indexable routes plus a
 * recommended crawl frequency and priority for each. Without this file Google
 * has to discover pages by crawling links — slow and unreliable for content
 * that lives behind interactions (e.g. event detail panels).
 *
 * Note: paths are written WITHOUT trailing slashes to match the canonical
 * URLs produced by `alternates.canonical` in each page's metadata. Mixing
 * slashed and non-slashed variants would create duplicate-content signals.
 */
const BASE_URL = "https://friendsforum.org"

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()

  return [
    {
      url: `${BASE_URL}`,
      lastModified: now,
      changeFrequency: "weekly",
      priority: 1.0,
    },
    {
      url: `${BASE_URL}/about`,
      lastModified: now,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/events`,
      lastModified: now,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/resources`,
      lastModified: now,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/forum`,
      lastModified: now,
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/contact`,
      lastModified: now,
      changeFrequency: "monthly",
      priority: 0.6,
    },
  ]
}
